# constants.py

# Wrist
WRIST = 0

# Thumb
THUMB_CMC = 1
THUMB_MCP = 2
THUMB_IP = 3
THUMB_TIP = 4
THUMB_FINGER = [THUMB_CMC, THUMB_MCP, THUMB_IP, THUMB_TIP]
THUMB = "Thumb"

# Index finger
INDEX_MCP = 5
INDEX_PIP = 6
INDEX_DIP = 7
INDEX_TIP = 8
INDEX_FINGER = [INDEX_MCP, INDEX_PIP, INDEX_DIP, INDEX_TIP]
INDEX = "Index"

# Middle finger
MIDDLE_MCP = 9
MIDDLE_PIP = 10
MIDDLE_DIP = 11
MIDDLE_TIP = 12
MIDDLE_FINGER = [MIDDLE_MCP, MIDDLE_PIP, MIDDLE_DIP, MIDDLE_TIP]
MIDDLE = "Middle"

# Ring finger
RING_MCP = 13
RING_PIP = 14
RING_DIP = 15
RING_TIP = 16
RING_FINGER = [RING_MCP, RING_PIP, RING_DIP, RING_TIP]
RING = "Ring"

# Pinky finger
PINKY_MCP = 17
PINKY_PIP = 18
PINKY_DIP = 19
PINKY_TIP = 20
PINKY_FINGER = [PINKY_MCP, PINKY_PIP, PINKY_DIP, PINKY_TIP]
PINKY = "Pinky"